Akoova!
WeareJH/m2-deploy-recipe pull request #2
Opened 2018-05-28 08:41 UTC by maxbucknell

Pls don't merge bbz.

2018-05-28 10:21 UTC, mikeymike approved these changes
All good pending some discussion with Akoova about the zip process

2018-06-05 13:57 UTC, dcabrejas requested changes

2018-06-05 13:57 UTC, dcabrejas commented on recipe/custom/zip.php
> +    run('cd {{release_path}} && tar -xzf deploy.tgz && rm {{bundle_name}}');
This is wrong !!!! WRONG!!!

2018-06-05 14:03 UTC, dcabrejas approved these changes

2018-06-05 14:09 UTC, merged